### ISSUE TITLE
Request public access to the function "getFaces" of a polyhedron object

### ISSUE THREAD

**Issue by liyangrock** [LLNL/axom#1014]
Sometimes one may want to obtain the polygon faces of a polyhedron object. However, there is no direct way to get the connectivity of polygon faces because `getFaces` is a private function in current version of `Polyhedron.hpp` (line.391-484).

Is it possible to make funtion `getFaces` public or provide an alternative method to achieve this?

**Comment by kennyweiss** [comment]
@liyangrock -- the axom team discussed this and decided to make the `getFaces()` function `public`, but to mark it as "experimental" to indicate that we might change the signature of the function in the future.

The current usage of `Polyhedron::getFaces()` is a bit awkward because the `primal::Polyhedron` class wasn't really designed to hold arbitrary polyhedra, but, rather, to hold the result of clipping reasonably simple convex polyhedra against each other (e.g. clipping a pair of `Tetrahedra` or an `Octahedron` and a `Tetrahedron`). 

It was further constrained to use preallocated buffers to allow using this class from either the CPU or the GPU. This required setting an arbitrary `MAX_VERTS` constant (currently set to 32).

Here is an example of calling and using `Polyhedron::getFaces()`:
https://github.com/LLNL/axom/blob/03d4c74ab518ec397804937b8fc81d2c50a1dd4e/src/axom/primal/geometry/Polyhedron.hpp#L514-L537

We will update this function and add some additional documentation and tests in the near future.

**Comment by liyangrock** [comment]
Thanks for your reply @kennyweiss . I already used it as a public function in my project now. I fully agree with your point that the current usage of `Polyhedron::getFaces()` is a bit awkard, and this is why I submitted this issue. It would be nice if an elegant usage can be provided in the future.

**Comment by kennyweiss** [comment]
@liyangrock -- we exposed the `Polyhedron::getFaces()` function and improved its testing in #1020

We intend to add some additional utility functions for the number of faces and edges when we work on https://github.com/LLNL/axom/issues/1022, under the assumption that the polyhedron is convex (or at least genus 0). These can be used to determine the sizes of the buffers that must be passed into the `getFaces()` function.

**Comment by liyangrock** [comment]
thanks @kennyweiss !
