### ISSUE TITLE
Possible logic error for exported targets

### ISSUE THREAD

**Issue by chapman39** [LLNL/axom#1243]
In the following code chunk, there is a possibility a target is found but explicitly disabled. For example, I don't think you would append openmp if `ENABLE_OPENMP=OFF` despite `OPENMP_FOUND=ON`. Perhaps change OR to AND?

https://github.com/LLNL/axom/blob/9410ed3db64ca1ab33b6053d8fd3e452c20bb562/src/cmake/AxomConfig.cmake#L165C23-L165C23

```cmake
set(_optional_targets cli11 fmt hdf5 lua openmp sol sparsehash)
foreach(_tar ${_optional_targets})
    string(TOUPPER ${_tar} _upper_tar)
    if(ENABLE_${_upper_tar} OR ${_upper_tar}_FOUND)
        list(APPEND _axom_exported_targets ${_tar})
    endif()
endforeach()
```

**Comment by white238** [comment]
This shouldn't have `openmp` in it. We purposefully do not make any targets depend on `openmp` due to the issue with generator expressions. This will change soon with the new BLT macro.

This loop handles multiple generated variables between TPLs and internal builtin TPLs. The TPLs set the `_FOUND` variables and without verifying it, I think `openmp` was the only one with an `ENABLE_` variable. This shouldn't cause an issue though because we are not setting `OPENMP_FOUND` and CMake's FindOpenMP.cmake sets `OpenMP_FOUND`.

Did you hit a bug that was showing a problem that made you look at this?

**Comment by chapman39** [comment]
@white238 One of the TPLs I was linking against had -fopenmp, which is what caused the error. The loop makes sense the way it is, since otherwise I wouldn't have noticed my bug.
