### ISSUE TITLE
Should the `AXOM_ANNOTATE_END` macro require a `name` parameter?

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#1315]
The `AXOM_ANNOTATE_BEGIN` and `AXOM_ANNOTATE_END` macros were added in https://github.com/LLNL/axom/issues/1312

During the review, @agcapps suggested that `AXOM_ANNOTATE_END` should not take a `name` parameter since it is not used in the implementation and can lead to code drift.

On the other hand, it can be useful to label the end using the same name as the beginning, in which case, we might prefer to keep the `name` parameter, rather than leaving it ambiguous or requiring a comment.

A third possibility might be to use the `name` parameter for internal bookkeeping within axom.

We should discuss this as a group.

**Comment by daboehme** [comment]
I'd generally recommend using `cali_begin_region(const char* name)` and `cali_end_region(const char* name)` for marking the regions. The `cali::Caliper` API is considered internal so there's a higher risk of things changing in the future, although it's not very likely here. The `cali_end_region` call checks if the given value matches the top of the Caliper region stack and gives an error if it doesn't. You can do the same with `cali::Caliper::end_with_value_check(const Attribute&, const Variant&)`, which is what `cali_end_region` does under the hood. That said your current version is going to be slightly faster since it skips this check.

**Comment by kennyweiss** [comment]
Thanks @daboehme -- in that case, I think I'll move it over to `cali_begin_region(name)` and `cali_end_region(name)`.

Any objections from others on the axom side?

**Comment by agcapps** [comment]
None from me.
