### ISSUE TITLE
Suggestion for sidre::IOManager API

### ISSUE THREAD

**Issue by gzagaris** [LLNL/axom#195]
I noticed some inconsistency in the API of the `sidre::IOManager` class, that may be confusing to some users:
- `sidre::IOManager::write()` accepts a string corresponding to the base file name with no extension. 

- `sidre::IOManager::read()`, however, expects the root file, which is `<basefile>.root`

Could both `write()` and `read()` take the same string argument, e.g., either just the base filename with no extension? or the root file?

This seems more intuitive and could enhance usability aspects of this class in application codes.

**Comment by kennyweiss** [comment]
I think it is that way because ``sidre::IOManager::write("foo")`` writes out several files -- including ``foo.root`` and the actual data files into a subdirectory named "foo".  The extensions for the data files are based on the ``sidre_protocol``.

When reading in files, ``sidre::IOManager::read("foo.root")`` only directly reads the root file ``foo.root`` file which lists the names of the data files (more specifically, the pattern for the data files).

Rather than changing the current behavior, perhaps ``sidre::IOManager::write()``  could be a bit more forgiving and peel off a trailing ``.root`` if it is present in the input?

**Comment by gzagaris** [comment]
> Rather than changing the current behavior, perhaps `sidre::IOManager::write()` could be a bit more forgiving and peel off a trailing `.root` if it is present in the input?

Yup, that works for me.
