### ISSUE TITLE
Add config option about exporting 'fmt' library

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#209]
``fmt`` (https://fmt.dev) is a string formatting library that ``axom`` includes as a built-in third party library. We configure ``fmt`` as a header-only library, which we export as an installation target.

Several users have expressed the desire to use their own copy of the ``fmt`` library, rather than ``axom``'s exported copy.

The easiest way to support this might be to introduce a configuration variable, e.g. ``AXOM_EXPORT_FMT`` (which defaults to ``TRUE``), that controls whether or not we export ``axom``'s version of ``fmt`` to users.

During a team meeting on 3/30/2020, there was a brief discussion about the possibility of symbol conflicts if a user code has a different version of ``fmt`` than ``axom``. This may require allowing users to supply an optional external ``fmt`` when configuring ``axom``.

**Comment by brunner6** [comment]
@kennyweiss It seems easiest (for me) and safest for me to provide an external fmt library.  If you provide one, even internally, I think my project is stuck using exactly the version you have, as you provide it.  I too fear symbol clashes or undefined behavior as all the weak symbols from the templates get magically resolved at link time.

Really, all of the TPLs should be capable of being externally provided, even if you want to provide convenience ones in your tarball.  (The exception to this might be very tightly integrated libraries like the set of Raja/Chai/Umpire.)

For my project, we we used fmt header only, I'm concerned that the code bloat and compile time hit would be enormous.  This was the initial impetuous for being able to switch versions of this library.   It _might_ be acceptable to use fmt provided by you if you let us configure the compile vs header-only.  Why not just use fmt's CMake instead of repackaging its version?

**Comment by white238** [comment]
Now that I look at the code, I am not entirely sure we need to do anything.  They would just not include the exported fmt-targets.cmake.

Please note I have not actually tried this.  We may need to alter our Axom target to not rely on the fmt target publically.

**Comment by kennyweiss** [comment]
Thanks for your feedback @brunner6.  

Here is some context:
For our internal use, we added a convenience header file ``fmt/fmt.hpp`` (https://github.com/LLNL/axom/blob/develop/src/thirdparty/fmt/fmt.hpp)  that includes our ``config.hpp`` before including the rest of the ``fmt`` headers. We set it up that way to make it easier to pass along our ``fmt`` configuration throughout ``axom`` without requiring lots of compiler defines on the compilation line. Since this seemed useful for other projects, we exported our ``fmt`` configuration to user projects.

Our current ``fmt`` configuration has two defines:
https://github.com/LLNL/axom/blob/17f71f750155f97e9b74a0df17f9a32718c8782d/src/axom/config.hpp.in#L95-L99

It sounds like it could be helpful if we either:
* Allowed users to pass in an external ``fmt``, e.g. via ``FMT_DIR``
* Allowed for ``fmt`` to be configured as a compiled library

OR
* Provide an option to disable exporting ``fmt`` (if necessary, as @white238 noted above).

For the first option, I have concerns about API changes between different versions of ``fmt`` breaking ``axom``'s compilation.  I know we had some issues when we upgraded to ``fmt@5.1`` (a few years ago).

For the second option, we'd have to ensure that there were no issues with clashing symbols.

**Comment by gzagaris** [comment]
Adding an option that indicates whether or not to export FMT may be a bit confusing since we always "require" our built-in TPLs (some components more than others).  If the built-in TPL is not exported and installed as axom expects it, it can lead to annoying compilation issues for some folks and would require a lot of donut donations to resolve.

I think what we want is the ability to specify an external directory for a built-in TPL and use that instead. FMT is only one instance of that. The same is true for all of our built-in TPLs. 

That is precisely one of the reasons I am always very conservative with TPL usage inside library code...
