### ISSUE TITLE
Unless SLIC is initialized, no messages appear from Axom

### ISSUE THREAD

**Issue by white238** [LLNL/axom#280]
When you don't initialize SLIC, all messages or assert's are turned into basically noops.  This caused me a lot of confusion before I figured this out and this has got to be confusing to users as well.

I propose two solutions but am open to others:

1) A warning that says SLIC has not been initialized and default to a basic SLIC instantiation. This way the users at least get something and can quiet it.  Maybe even give some helper function in Axom to setup SLIC.
2) Don't warn but default to std::cout and std::err.

**Comment by rhornung67** [comment]
👍

**Comment by gzagaris** [comment]
I think I prefer (2) -- This would (or could) also resolve the issue where SLIC is initialized, but, it there are no streams attached to the logger, which wouldn't produce any log messages either. It's also easier to implement and hide under our macros too.

With (1) we can mitigate this, but, then it requires the calling application to call something like `axom::init(MPI_Comm my_comm)` and consequently `axom::finalize()`. Ultimately, I don't have a  real issue with that either, but, if they forget to call `axom::init()`, then they would still not get any messages.

What I don't like about (2) is that it would require an extra-if check which could hinder performance if the caller is doing logging  in a tight loop. But, then again, they shouldn't be doing logging inside a tight kernel loop in the first place, so that is probably fine...

I am open to better alternatives if anyone has other suggestions.

**Comment by cyrush** [comment]
In this case, do error also become also no-ops?  
@mclarsen hit multiple issues where errors (which should be fatal) were ignored when Sidre + SLIC were in the mix.

**Comment by white238** [comment]
Without initializing SLIC, no messages or asserts at all come out of any SLIC call.  I don't know if we have any non-SLIC messages in Axom.

**Comment by gzagaris** [comment]
> In this case, do error also become also no-ops?
> @mclarsen hit multiple issues where errors (which should be fatal) were ignored when Sidre + SLIC were in the mix.

Yes, if SLIC is not initialized, errors become no-ops. We could fix this with (2) by calling `axom::utilities::processAbort()` at the macro level, instead from within the Logger.

**Comment by rhornung67** [comment]
If Slic is not initialized, initialize a simple logger (std::cout) and emit a warning message about this.

**Comment by agcapps** [comment]
Closed with MR #799
