### ISSUE TITLE
Add unit tests for SCR examples

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#311]
We should add the `scr` examples as unit tests.

This will likely require adding some `scr` checkpoint files to the `axom_data` repository: https://github.com/LLNL/axom_data

**Comment by rhornung67** [comment]
@nselliott will touch base with Adam M. about his PR.

**Comment by nselliott** [comment]
The example spio_IO_SCR_Checkpoint_ex example has unit test code added into it, in order to keep all SCR testing in one executable, as errors occur if two SCR-enabled executables get launched in parallel during a `make test` run.  I think this satisfies the request in this issue.  Any further SCR-based unit testing should be inserted into this example.
