### ISSUE TITLE
Loosen HDF5 variants in spack package

### ISSUE THREAD

**Issue by white238** [LLNL/axom#331]
Our hardcoded HDF5 are causing problems in down stream projects (like Serac).  These need to be revisited and loosened.

**Comment by cyrush** [comment]
interested in the details here, is it that other packages conflict due to spack's concretizer?

We did relax the conduit hdf5 constraints for CEED. Probably the same fix.

https://github.com/spack/spack/blame/02dc84a2b3c4f5737e205b25088830c7ad0733ea/var/spack/repos/builtin/packages/conduit/package.py

**Comment by white238** [comment]
It was specifically the "~mpi" on hdf5 (we inherited conduit's constraints early on im pretty sure and they were never revisited).

**Comment by cyrush** [comment]
got it, I am wondering what package want's HDF5 mpi support?  If Serac is using Sidre -- it doesn't need HDF5 + mpi.

I would say it can't hurt, but it does introduce an mpi link dep into otherwise serial code.

**Comment by white238** [comment]
Apparently adding +netcdf to mfem caused the following conflict:

```
axom requires hdf5 variant ~mpi, but spec asked for +mpi[ERROR: failure of spack install/dev-build]
```

I am just reporting what a user said to me.  I can put them in touch with you if you like. Or spend time trying to reproduce it at a later date.

**Comment by gzagaris** [comment]
I think the issue may be that `netcdf` requires HDF5 MPI support, but, axom explicitly requires a non-MPI hdf5 (?) 

- We should be able to use an MPI HDF5 even if we don't make calls to the parallel HDF5 API, right? 
- Is this restriction enforced in the spack package for Axom?

**Comment by cyrush** [comment]
@white238 thanks netcdf context helps, just want to have an understanding of the constraints driving this.
@gzagaris  the answer to both of your question is yes, we should be able to drop the ~mpi constraint for axom.

mpi enabled hdf5 should be fine, but things might still go wrong due to linking. I say this b/c we haven't tested how or if that new dep will propgate through FindHDF5, etc. Takes us down a new path.
