### ISSUE TITLE
Expose AXOM_DEBUG macro definition in axom/config.hpp file

### ISSUE THREAD

**Issue by rhornung67** [LLNL/axom#440]

**Comment by white238** [comment]
The multi CMake config build complicates this.

https://github.com/LLNL/axom/blob/d8f5f41c830453a4ceba6711de90dc9f0f71adee/src/cmake/CMakeBasics.cmake#L22-L34

This cannot be added to the config header due to one header being used for all configs.  Another possible solution is to utilize a generator expression and add it to the Core library.

**Comment by kennyweiss** [comment]
After some experimenting with attempting to add `AXOM_DEBUG` to `config.hpp`, I have to agree with @white238's point above about multi-config generators and went with his solution (adding the define to the `core` target) in #699

**Comment by kennyweiss** [comment]
Fixed underlying issue in #699.

I was not able to add to `axom/config.hpp` due to issues related to how multi-config generators work (see above), but we now export the `AXOM_DEBUG` compiler define with the `axom`  CMake target.
