### ISSUE TITLE
Semantics of ArrayView and const

### ISSUE THREAD

**Issue by kennyweiss** [LLNL/axom#732]
Should we be able to modify the data within a const ArrayView?

We should probably follow the semantics of std::span

**Comment by kennyweiss** [comment]
This was discussed here: https://github.com/LLNL/axom/issues/633#issuecomment-964546470

**Comment by kennyweiss** [comment]
Let's look at what RAJA Views are doing as well.

**Comment by rhornung67** [comment]
Here are some bread crumbs for what we do in RAJA. Note that this looks more complicated than it needs to be. The reason is that this stuff is used to make view data access, via an operator that takes a tuple of indices based on dimensionality of the view (e.g., view(i, j, k)), generic. That is, indices can be C++ language defined scalar integral types, strongly typed (e.g., i, j, k are distinct types to prevent indexing errors at compile time), or types used for SIMD vector, matrix, tensor based iterates. 

Here's the generic operator (i.e., view(i,j,k)) definition: https://github.com/LLNL/RAJA/blob/develop/include/RAJA/util/TypedViewBase.hpp#L334

Here's the definition of the method to create the view return value: https://github.com/LLNL/RAJA/blob/develop/include/RAJA/util/TypedViewBase.hpp#L151

Other relevant definitions for 'ViewReturnHelper', etc. are in the RAJA/include/util/TypedViewBase.hpp file.
