### ISSUE TITLE
Error message for `validValues` should list correct and given values

### ISSUE THREAD

**Issue by white238** [LLNL/axom#736]
Inlet's error message in this case could be improved in this failure case.  When a primitive type is given a set of `validValues` and the user gives a bad value in the input file.  It would be nice to have Inlet output what is valid.

For example, in the following badly formed Serac input file:

```
main_mesh = {
    type = "generate",
    elements = {x = 10, y = 10}
}
```

errors with:

```
$ serac -i ../examples/simple_conduction/conduction.lua 
Logger activated: serac_serial_logger

******************************Command Line Options******************************
Input File: ../examples/simple_conduction/conduction.lua
Output Directory: conduction
********************************************************************************

[WARNING (axom-0.6.0/spack-src/src/axom/inlet/Field.cpp:454)]
[Inlet] Value did not meet range/valid value(s) constraints: input_file/main_mesh/type

[ERROR (repo/src/drivers/serac.cpp:69)]
Input file failed to verify.
** StackTrace of 5 frames **
Frame 1: axom::slic::logErrorMessage(std::string const&, std::string const&, int)
Frame 2: serac::defineInputFileSchema(axom::inlet::Inlet&)
Frame 3: main
Frame 4: __libc_start_main
Frame 5: serac() [0x7680f9]
=====
```

I would prefer something like:

```
[WARNING (axom-0.6.0/spack-src/src/axom/inlet/Field.cpp:454)]
[Inlet] Given value 'generate' for 'input_file/main_mesh/type' did not meet valid value(s) constraints: "ball", "box", "disk", "file"

[ERROR (repo/src/drivers/serac.cpp:69)]
Input file failed to verify.
** StackTrace of 5 frames **
Frame 1: axom::slic::logErrorMessage(std::string const&, std::string const&, int)
Frame 2: serac::defineInputFileSchema(axom::inlet::Inlet&)
Frame 3: main
Frame 4: __libc_start_main
Frame 5: serac() [0x7680f9]
=====
```

**Comment by joshessman-llnl** [comment]
Changing this would probably involve moving the error messages from `Field::verify` to `Field::checkRange` and `Field::searchValidValues`.

Note that this would require piping the list of VerificationErrors those extra two layers down the stack as well as slightly tweaking the path logic since those latter two methods operate on the "value" (or "default_value") within the Group that corresponds to the `Field` - I think we'd want the error message to use `view->getPath()` instead of the current `grp->getPathName()`.
