### ISSUE TITLE
Output hierarchy details

### ISSUE THREAD

**Issue by rhornung67** [LLNL/axom#765]
We should have a way to output the details of a View, a Group, a Group hierarchy, etc. including associated buffer information to both std out and also JSON (via Conduit?).  We currently have ways to do parts of this but it's not complete or consistent. This would help users understand usage better and also help the solve problems when things go awry.

**Comment by ltaylor16** [comment]
Should this functionality be in the ``sidre/core`` directory, or should we create another directory to add functionality which builds on the core API?

**Comment by rhornung67** [comment]
I could go either way. Since the core directory contents are not very large, this may not add a bunch of new code. On the other hand, keeping as much as possible out of the existing classes would make things more flexible (e.g., adding new class methods, vs. external methods calling class methods). Thoughts on how flexible we can/need to be with this?

**Comment by ltaylor16** [comment]
We've talked a lot about building functionality on top of the the core.  This is a good example and might encourage more things to be built this way if we started by creating a directory and adding it to the build system.
Otherwise we'll keep adding one more small thing to core until it becomes cluttered and unmanageable.

**Comment by cyrush** [comment]
I agree, also doing it outside also is a good way to make sure core provides everything necessary to support this info. (I think it should, but this would be strong confirmation)

**Comment by rhornung67** [comment]
Add a new "debug" or "metadata" protocol.

**Comment by nselliott** [comment]
I've come up with a plan to add two new protocols for `Group::save()` to create user-readable output of the hierarchy.

`sidre_layout_json` would be like `sidre_conduit_json` minus the Buffer array data.  It would save the full Sidre hierarchy and write out all of the datatype schemas and show the mapping between Views and Buffers, but the actual arrays would be left out.

`conduit_layout_json` would be like `conduit_json`.  It would save the Sidre hierarchy after it it translated to a conduit Node via `createNativeLayout` and again write out all of the datatype schemas without the actual data.  It would not have View-Buffer mapping information, because none of the `conduit_*` protocols save that information.

The protocol names are open to any suggested name changes.

These would be valid protocols for `save()` but would not be useful for `load()`.

**Comment by cyrush** [comment]
Sounds good!

**Comment by rhornung67** [comment]
@nselliott sounds like a good plan!
